all: noop.cpp number.cpp removetag.cpp removetag0.cpp
	mkdir ../bin
	g++ noop.cpp -o ../bin/noop -Wall
	g++ number.cpp -o ../bin/number -Wall
	g++ removetag.cpp -o ../bin/removetag -Wall
	g++ removetag0.cpp -o ../bin/removetag0 -Wall
	cp /bin/ls ../bin/ls
	cp /bin/cat ../bin/cat
