#!/bin/sh -e

echo "Starting test for file:$1 ..."

# replace stderr to stdout
cp $1 __tmp.l
sed -e "s/stderr/stdout/" __tmp.l > __tmp.pass.l
rm -f __tmp.l

# move source to core directory
mv __tmp.pass.l ./core/scanner.l

# run test
make -C ./core/ test

# clean temp files
rm -f ./core/scanner.l
rm -f ./core/scanner

